### ISSUE TITLE
Backend gitignore

### ISSUE THREAD

**Issue by RodrigoNovais** [solrachix/Be-The-Hero#1]
It is missing a `.gitignore` file to your backend folder

Dotenv files should not been sent to the repos once it can contain sensitive info
You can keep a `.env.example` as template if needed

You can easily create gitignore files using https://www.gitignore.io/
Based on what I saw I recommend using [this](https://www.gitignore.io/api/node,dotenv) as your .gitignore file

About removnig sensitive data that has unintentionally commited, you can keep [this link](https://help.github.com/pt/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

Be aware, security first

**Comment by solrachix** [comment]
Muito bem visto @RodrigoNovais 
Arrumado!!
